include:
  - ../db-proc/compose.yaml

services:
  api-proc:
    build: .
    container_name: api-proc
    ports:
      - "${API_PORT}:${API_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT}/healthcheck" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 50s
    networks:
      - net-proc
    depends_on:
      - db-proc
networks:
  net-proc:
    driver: bridge
